### ISSUE TITLE
contributer names inside of constants.ts are broken

### ISSUE THREAD

**Issue by catsstuffs** [sourcelocation/Vencord-no-wokeness#2]
### Content

src/utils/constants.ts shows your really awesome ctrl+f skills, you probably shouldnt be removing the contributor names here as this also breaks contributor badges on profiles as well
![image](https://github.com/user-attachments/assets/d1bf789d-eb16-47a2-a011-5f0183fe462c)
if you mark it wontfix, its okay to hate the woke foss mob ❤️

### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by sourcelocation** [comment]
Laugh at this user
